### ISSUE TITLE
支持 prettier

### ISSUE THREAD

**Issue by bosens-China** [lint-md/lint-md#108]
如题，prettier3.0版本之后不支持自动化格式中英文空格，这个项目虽然可以通过cli的形式来修复，但是不够通用，prettier已经有足够的插件等生态，接入prettier可以直接完成编写格式化等工作。

**Comment by hustcc** [comment]
cli 下面有一个 core 包，可以用这个来封装一个插件，如果愿意，也可以统一放到这个 group 中，目前已经有 eslint 和 vscode 插件了。

**Comment by bosens-China** [comment]
> cli 下面有一个 core 包，可以用这个来封装一个插件，如果愿意，也可以统一放到这个 group 中，目前已经有 eslint 和 vscode 插件了。

已经集成完毕 https://github.com/bosens-China/prettier-plugin-lint-md 不过不知道如何放到group下

**Comment by hustcc** [comment]
> > cli 下面有一个 core 包，可以用这个来封装一个插件，如果愿意，也可以统一放到这个 group 中，目前已经有 eslint 和 vscode 插件了。
> 
> 已经集成完毕 https://github.com/bosens-China/prettier-plugin-lint-md 不过不知道如何放到group下

已经添加你的 group 权限，你看看提醒，然后同意即可，然后就可以移动进来。

**Comment by bosens-China** [comment]
可以，添加进来了🎉

**Comment by wenfangdu** [comment]
火钳刘明
