### ISSUE TITLE
标题末尾符号判断有误

### ISSUE THREAD

**Issue by PassionPenguin** [lint-md/lint-md#57]
标题中符号判断有误：

首先要弄清楚的是，标题末尾能不能用问号。

黄伯荣、廖序东主编的《现代汉语》对标点符号的用法作了如下的说明：

> "现在通行的标点符号有十四种，分为点号和标号两大类。句号、问号、感叹号、逗号、顿号、分号、冒号属于点号，引号、括号、破折号、省略号、书名号、着重号、间隔号属于标号。
> "点号主要是表示语言中种种停顿的。标号主要是标明词语或句子的性质和作用的。
> "也就是说，由于文章标题末尾是不需要停顿的，因此不能用逗号、句号等点号；但表明句子性质和作用的标号是可以用的，常用的如省略号。
> "而问号和感叹号两种点号也兼属标号：就它表示问句、感叹句末了的停顿而言，是点号；就它表示疑问、感叹的性质而言，是标号。"

（同上）据此可知，标题末尾是可以用问号、省略号、叹号的。

<img width="1009" alt="Screen Shot 2021-02-02 at 10 56 38 AM" src="https://user-images.githubusercontent.com/41184947/106545973-577eab00-6545-11eb-82fe-a5a052697309.png">

**Comment by hustcc** [comment]
这个依据厉害，可以通过配置文件关闭吧！另外，也可以 pr 来默认关闭这个规则吧~

**Comment by PassionPenguin** [comment]
然鹅....这只是trailing啊，我看看能不能fix，毕竟末尾不能出现句号逗号这些的嘛

**Comment by yuzhanglong** [comment]
刚刚看了下，这个官方的规范标准也允许的，下个版本会放开部分标点符号的约束。
<img width="879" alt="image" src="https://user-images.githubusercontent.com/56540811/196346589-7b341204-dee8-458a-80e3-052163da2fdf.png">

原文：（附录 B 末尾）
http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/201001/t20100115_75611.html

**Comment by PassionPenguin** [comment]
> 刚刚看了下，这个官方的规范标准也允许的，下个版本会放开部分标点符号的约束，感谢 @PassionPenguin 的建议。 <img alt="image" width="879" src="https://user-images.githubusercontent.com/56540811/196346589-7b341204-dee8-458a-80e3-052163da2fdf.png">
> 
> 原文：（附录 B 末尾） http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/201001/t20100115_75611.html

年代久远2333，辛苦维护了~

**Comment by yuzhanglong** [comment]
@PassionPenguin 由于近几个月忙于秋招无暇维护 😭，实在抱歉，感谢等待这么长时间~

现在你可以使用最新版的 lint-md CLI 工具,目前处于 beta 状态，欢迎试用：https://github.com/lint-md/lint-md#lint-markdown-20-beta。**对于标题允许问号、感叹号、省略号的结尾**。

主要的变动有：
1. 重构文本修复算法，fix 能力性能提升上百倍。
2. 底层 Markdown 解析库 remark 迁移至最新版。
3. 支持多线程 lint & fix。
4. 体验更好的命令行输出提示。
5. 项目架构完全重构，代码质量大幅提升，更方便 contribute😄

bug 或建议欢迎到 https://github.com/lint-md/lint-md/issues 提出。
