### ISSUE TITLE
Error 没有让 github action 停止执行

### ISSUE THREAD

**Issue by yinzixie** [lint-md/lint-md#67]
出现了error，为啥 github action 继续执行了？

![image](https://user-images.githubusercontent.com/48106713/140631403-980aa92d-cd38-47a3-9ebe-122f3431e649.png)

**Comment by yuzhanglong** [comment]
贴一下这个action执行的地址可以吗（如果方便的话）

**Comment by yinzixie** [comment]
不好意思，私人仓库没法贴出来。
但是你们提供的那个可以直接引用的action是没问题的，但是自己用命令是有问题。这一点不仅体现在action上在 lint-stage 中跑也是一样的效果，有error但不会退出。

**Comment by yuzhanglong** [comment]
@yinzixie 这个问题已经在 v0.1.6 修复，warning 默认会中断 ci，可以加上 -s 参数让 warning 不阻断。

**Comment by yinzixie** [comment]
不是啊，我说的是出现了 error 但是却没有阻断ci，而不是说warning会中断。。。。。

**Comment by yuzhanglong** [comment]
> 不是啊，我说的是出现了 error 但是却没有阻断ci，而不是说warning会中断。。。。。@yuzhanglong

我知道，只是加了个配置嘛，默认给开启了~

**Comment by yuzhanglong** [comment]
@yinzixie 抱歉，可能我没描述清楚，我的意思最新版本 error 和 warning 默认情况都会中断，但是加上 -s 参数则 warning 不中断

**Comment by yinzixie** [comment]
好的，我明白了，我是用 lint-md/cli 命令调用的，这个库有没有一起修复呢？

**Comment by yuzhanglong** [comment]
> 好的，我明白了，我是用 lint-md/cli 命令调用的，这个库有没有一起修复呢？

嗯

**Comment by yinzixie** [comment]
哦哦~，我看明白了，你在 cli 那里回复了。感谢，感谢。
