### ISSUE TITLE
README.md 中大小写不规范问题

### ISSUE THREAD

**Issue by iwill** [lint-md/lint-md#73]
请留意英文大小写问题：

- ci 都应该是 CI，固定的缩写格式
- List 都应该是 list
- markdown 都应该是 Markdown
- vscode 一般应该是 VS Code
- webhook 都应该是 WebHook

**Comment by yuzhanglong** [comment]
谢谢提醒~ 
现在项目正在重构，待重构完成一并修改。

**Comment by yuzhanglong** [comment]
fixed: https://github.com/lint-md/lint-md/commit/d6a2cfdc356bfda2b2954ff3be62ec48124f93eb
