### ISSUE TITLE
Front Matter 中的内容被认为是标题而不是 yaml 进行了处理

### ISSUE THREAD

**Issue by gadfly3173** [lint-md/lint-md#75]
Front Matter 中的内容被认为是标题而不是 yaml 进行了处理，可以考虑忽略掉什么的

![image](https://user-images.githubusercontent.com/28685179/156327898-aa36221d-becf-4996-85ec-98a399e4fa6a.png)

**Comment by yuzhanglong** [comment]
会考虑的，你看下这个，我的处理想法，可以提提意见：https://github.com/lint-md/cli/issues/4#issuecomment-1094557793
