### ISSUE TITLE
请问是否加入 cluster / worker， 提高多核利用率，加快处理速度？

### ISSUE THREAD

**Issue by luojiyin1987** [lint-md/lint-md#78]

**Comment by yuzhanglong** [comment]
> 我在参与 [把 freecodeCamp 文章翻译成中文的项目](https://github.com/freeCodeCamp/news-translation) 该项目用到你维护的工具 本地 运行 `npm run lint` 比较慢。

好的。

@hustcc 我的那个 PR 辛苦 cr 一下，方便继续推进我们的 remark 迁移和性能优化。

**Comment by yuzhanglong** [comment]
@luojiyin1987 我试了下，扫完全文大概是 20 多秒，你那边怎么样？（Apple M1 Pro，8 核心）

**Comment by luojiyin1987** [comment]
@yuzhanglong   在window10 上， AMD 4750u（8核16线程）   40G 内存    Node 版本  17.9.0     运行 `npm run lint`  大概13秒
                           在 ubuntu 22.04    i5-3320M      (2核4核)           12G 内存    Node 版本  16.18.0    运行 `npm run lint`  大概23秒

主要执行  `npm run  format`  比较久， cup 的负载并不高， 不过工作交给CI，问题不大。
window 268 多秒，约4分钟多。                                   
Linux 要 404 多秒，大概6分钟多。

**Comment by yuzhanglong** [comment]
感谢你的回复。

刚刚尝试去实现了多线程方案，做多线程难度不大，但是在某些状态下会有一些问题，那就是**分配给某个线程的任务时间复杂度是不确定的**，我刚刚拿你提到的 [把 freecodeCamp 文章翻译成中文的项目](https://github.com/freeCodeCamp/news-translation) 做了测试，一共 400 多篇文档，我将其分成 8 组（8 为 CPU 核心数目） ，理论上性能提高八倍，却发现速度怎么也提不上来，原因是某一组的 lint 时间远远超过了其他组，成为了 “短板”，其它组对应线程都处于饿死状态，**而最终结果的产出必须等待所有 lint 都完成**。

于是我尝试去写一个“分组算法”，测试的结果如下图：让每一组 Markdown 的字符串长度尽可能接近，重复上述操作，仍然存在所谓的“短板”，可以看出 在某些情况下 lint 的速度**和字符串长度并不是强相关**的，且这个具体因素不太好找，**可能**和这篇 Markdown 文本命中的 lint 规则** 或者 **AST 的结构**有关，而这些因素是不太方便在这个时机获取的。

<img width="718" alt="image" src="https://user-images.githubusercontent.com/56540811/200115199-73253554-1f8d-4160-b1cc-179b2ab518d4.png">


不知道这是不是一个偶然的 Case，npm run format 我还没试过，可能会好一些。

最终我会在命令行中加一个可选的参数 threads，默认还是维持单线程，如果需要多线程可以手动配置相应的命令行。

**Comment by yuzhanglong** [comment]
@luojiyin1987 由于近几个月忙于秋招无暇维护 😭，实在抱歉，感谢等待这么长时间~

现在你可以使用最新版的 lint-md CLI 工具,目前处于 beta 状态，欢迎试用：https://github.com/lint-md/lint-md#lint-markdown-20-beta

本次重构重写了文本 fix 算法（本项目速度慢的真正瓶颈），经过测试 [把 freecodeCamp 文章翻译成中文的项目](https://github.com/freeCodeCamp/news-translation)，在单线程环境下，新版 npm run format 的时间为 20 多秒，另外支持多线程配置，具体可参阅 README。


主要的变动有：
1. 重构文本修复算法，fix 能力性能提升上百倍。
2. 底层 Markdown 解析库 remark 迁移至最新版。
3. 支持多线程 lint & fix。
4. 体验更好的命令行输出提示。
5. 项目架构完全重构，代码质量大幅提升，更方便 contribute😄

bug 或建议欢迎到 https://github.com/lint-md/lint-md/issues 提出。
