### ISSUE TITLE
.lintmdrc 文件有提供对指定md文件不进行lint校验的配置么

### ISSUE THREAD

**Issue by Trojan0523** [lint-md/lint-md#79]
如题， Help want，想请问下作者是否有提供配置属性支持指定.md文件不进行校验的功能呢

**Comment by yuzhanglong** [comment]
提供了，cli 仓库里面有文档：https://github.com/lint-md/cli#%E9%85%8D%E7%BD%AE

**Comment by Trojan0523** [comment]
@yuzhanglong 谢谢您
