### ISSUE TITLE
bug or question

### ISSUE THREAD

**Issue by Mister-Hope** [lint-md/lint-md#98]
Can anybody explain why the tool is formatting the following line, and which rule it's triggering?

![image](https://github.com/lint-md/lint-md/assets/33315834/18f7729e-5e83-4ee6-9972-b9e1ca16fb0c)

I don't think it makes sense.

**Comment by yuzhanglong** [comment]
I will fix it these days

**Comment by yuzhanglong** [comment]
@Mister-Hope fixed, please use @lint-md/cli@2.0.0
